version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  assignees:
  - dciborow
  allow:
  - dependency-type: direct
  - dependency-type: indirect
