# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: AGAI-Industrial-AI
    type: git
    name: One/AGAI-Industrial-AI

steps:
- checkout: self
- checkout: AGAI-Industrial-AI

- script: |
    ls
  displayName: 'Run a multi-line script'
