# This is a basic workflow that is manually triggered

name: Publish Container Update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

jobs:
  update_container:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install virtualenv

        add-apt-repository -y ppa:ubuntugis/ppa \
        && apt install -y \
          gdal-bin libgdal-dev
    
    - name: Update Container
      run: |
        git clone https://${{ secrets.ADO_USER }}:${{ secrets.ADO_PASSWORD }}@cloudes.visualstudio.com/CDPX/_git/CDPX-Linux-Images
        cd CDPX-Linux-Images/src/user/agai/agai-template-ubuntu-1804/latest/requirements
        ./generate.sh -s .
        
        git add -A
        git commit -m "Updating Container"
        git push origin --force master:dciborow/container-update
