# This is a basic workflow that is manually triggered

name: Publish Container Update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

jobs:
  update_container:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |          
          az extension add --name azure-devops
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install virtualenv

        sudo add-apt-repository -y ppa:ubuntugis/ppa \
        && sudo apt install -y \
          gdal-bin libgdal-dev
    - name: Update dependencies
      run: |
        git clone https://${{ secrets.ADO_USER }}:${{ secrets.ADO_PASSWORD }}@cloudes.visualstudio.com/CDPX/_git/CDPX-Linux-Images
        cd CDPX-Linux-Images

        cd src/user/agai/agai-template-ubuntu-1804/latest/requirements
        ./generate.sh -s .

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          cd CDPX-Linux-Images
          git config --global user.email "dciborow@microsoft.com"
          git config --global user.name "Daniel Ciborowski"

          git add -A
          git commit -m "Updating Container"

          git push origin --force master:${{ secrets.ADO_USER }}/container-update
          
          az login --service-principal -u ${{ secrets.AZURE_USER }} -p ${{ secrets.AZURE_PASS }} -t ${{ secrets.AZURE_TENANT }}
          az repos pr create \
            --auto-complete true \
            --organization https://cloudes.visualstudio.com \
            --project CDPX \
            --repository CDPX-Linux-Images \
            --source-branch ${{ secrets.ADO_USER }}/container-update \
            --target-branch master
