# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_container:
    runs-on: ubuntu-latest
    steps:
    - name: Update Container
      run: |
        git clone https://${{ secrets.ADO_USER }}:${{ secrets.ADO_PASSWORD }}@cloudes.visualstudio.com/CDPX/_git/CDPX-Linux-Images
        cd CDPX-Linux-Images/src/user/agai/agai-template-ubuntu-1804/latest/requirements
        ./generate.sh -s .
        
        git add -A
        git commit -m "Updating Container"
        git push origin --force master:dciborow/container-update
